### ISSUE TITLE
Electron Packagerでexe化した場合のみウィンドウを閉じてもプロセスが終了されない

### ISSUE THREAD

**Issue by siloneco** [siloneco/Virtual-Quick#1]
## 概要
タイトルの通り、Electron Packagerでexe化した場合のみプロセスが終了されないバグを確認済み  
開発フォルダで
```
electron ./
```
を実行して起動した場合はウィンドウを全て閉じた場合にプロセスが終了されるが、
```
electron-packager ./Virtual-Quick Virtual-Quick --platform=win32 --arch=x64 --electronVersion=8.2.3 --overwrite
```
を使用し exe 化したものを、コマンドプロンプトから
```
Virtual-Quick.exe
```
で起動し、ウィンドウを全て閉じたところプロセスが終了されていないことが分かる。

## 環境
* electron@8.2.3
* electron-packager@14.2.1
* windows10

**Comment by taizan-hokuto** [comment]
間違っていたらすみませんが、

https://stackoverflow.com/questions/23258421/how-to-stop-app-that-node-js-express-npm-start/39128820
↑に該当するのかなと思いました。

一番簡単な手順として、
Ctrl+Cで、コマンド受付状態に戻らないでしょうか？

※Command Prompt または Power Shell等、「別のシェル」からpathを指定してelectronアプリを立ち上げた場合、
ウィンドウ上で終了してもnode.jsのプロセス自体は残り続けるということのようです。

（終了するには、npm stopまたはそれに準じたコマンドでサーバーを停止する必要あり？package.jsonにはstopコマンドがない場合は、npm stopと打ってもエラー発生で終了します。）

**Comment by siloneco** [comment]
なるほど、つまりexeダブルクリックで起動した場合は正常に終了されるため問題ないという感じですかね

**Comment by taizan-hokuto** [comment]
そうですね。
こちらでビルドして試した限りでは、exeファイルを直接ダブルクリックして起動した後、ウィンドウを閉じたらプロセスは正常に終了していました。

**Comment by siloneco** [comment]
なるほど、それなら問題ないですね。情報提供助かりました！
